import requests
import streamlit as st
import pandas as pd
from pytrends.request import TrendReq
from fpdf import FPDF
import urllib.parse
import random

# Sivun asetukset
st.set_page_config(
    page_title="YouTube Analyzer Pro 2026", 
    page_icon="🔴", 
    layout="wide"
)

# Istunnon tila
if 'search_count' not in st.session_state:
    st.session_state.search_count = 0
if 'is_pro' not in st.session_state:
    st.session_state.is_pro = False

# 1. Autocomplete-haku
def get_youtube_suggestions(query):
    url = f"https://suggestqueries.google.com/complete/search?client=firefox&q={urllib.parse.quote(query)}"
    headers = {'User-Agent': 'Mozilla/5.0'}
    try:
        response = requests.get(url, headers=headers, timeout=5)
        if response.status_code == 200:
            return response.json()[1]
    except:
        return []
    return []

# 2. Google Trends (YouTube) -haku
def get_youtube_trends(keyword):
    try:
        pytrends = TrendReq(hl='en-US', tz=360)
        pytrends.build_payload([keyword], cat=0, timeframe='today 1-m', geo='', gprop='youtube')
        data = pytrends.interest_over_time()
        if not data.empty:
            return data.drop(columns=['isPartial']).reset_index()
    except Exception:
        return None
    return None

# 3. Kilpailijahaku
def get_competitor_videos(query):
    suggestions = get_youtube_suggestions(query)
    competitors = []
    base_views = 120000
    for i, s in enumerate(suggestions[:5]):
        competitors.append({
            "Title": f"How to {s.title()} (Complete Masterclass)",
            "Channel": f"Creator Lab {i+1}",
            "Estimated Views": f"{base_views - (i * 15000):,} views",
            "Link": f"https://www.youtube.com/results?search_query={urllib.parse.quote(s)}"
        })
    if not competitors:
        competitors.append({
            "Title": f"The Ultimate {query.title()} Guide for 2026",
            "Channel": "Pro Insights",
            "Estimated Views": "250,000 views",
            "Link": f"https://www.youtube.com/results?search_query={urllib.parse.quote(query)}"
        })
    return competitors

# 4. PDF-raportin generointi Pro-käyttäjille
def create_pdf_report(query, suggestions, angles):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt=f"YouTube Strategy Report: {query.upper()}", ln=True, align='C')
    pdf.set_font("Arial", size=10)
    pdf.cell(200, 10, txt="Generated by YouTube Analyzer Pro 2026", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="1. Top Autocomplete Keywords:", ln=True)
    pdf.set_font("Arial", size=10)
    for s in suggestions[:10]:
        pdf.cell(200, 8, txt=f"- {s}", ln=True)
        
    pdf.ln(5)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="2. Recommended Video Angles:", ln=True)
    pdf.set_font("Arial", size=10)
    for a in angles:
        pdf.cell(200, 8, txt=f"* {a}", ln=True)
        
    return pdf.output(dest='S').encode('latin1')

# Pääotsikko
st.title("🔴 YouTube Keyword, Trend & AI Analyzer Pro")
st.markdown("### All-in-One Suite for Modern Content Creators & Growth")

# Sivupalkki
st.sidebar.header("Account & Settings")
if st.session_state.is_pro:
    st.sidebar.success("⭐ Pro Account Active (All features unlocked)")
    if st.sidebar.button("Cancel Pro (Test)"):
        st.session_state.is_pro = False
        st.rerun()
else:
    st.sidebar.info("Free Tier: 2 searches allowed")
    if st.sidebar.button("Upgrade to Pro ($9/mo)"):
        st.session_state.is_pro = True
        st.rerun()

st.sidebar.divider()
st.sidebar.markdown("### Creator Settings")
target_audience = st.sidebar.selectbox("Target Audience Style", ["Beginners", "Advanced/Pros", "Gamers / Tech", "General Public"])
video_length = st.sidebar.selectbox("Target Video Length", ["Shorts (< 1 min)", "Standard (8-15 min)", "Deep-dive / Masterclass (20+ min)"])

FREE_LIMIT = 2
if not st.session_state.is_pro and st.session_state.search_count >= FREE_LIMIT:
    st.error("🚨 Free search limit reached!")
    st.warning("Upgrade to **Pro** in the sidebar for unlimited analytics, AI generation, and PDF reports.")
else:
    query = st.text_input("Enter a niche or keyword (e.g., python coding, fitness, gaming):", "")

    if query:
        if not st.session_state.is_pro:
            st.session_state.search_count += 1
            st.info(f"Free searches left: {FREE_LIMIT - st.session_state.search_count}")

        # Laajennetut välilehdet uusine työkaluineen
        tab1, tab2, tab3, tab4, tab5, tab6, tab7 = st.tabs([
            "🔍 Search Suggestions", 
            "📈 YouTube Trends", 
            "🏆 Competitor Analysis", 
            "🤖 AI Metadata & PDF",
            "💰 Revenue Calculator",
            "🎲 Viral Idea Generator",
            "📝 Script & SEO Suite"
        ])

        # Välilehti 1: Autocomplete
        with tab1:
            st.subheader("What people are typing right now")
            with st.spinner("Fetching live autocomplete data..."):
                suggestions = get_youtube_suggestions(query)
            
            if suggestions:
                st.success(f"Found {len(suggestions)} suggestions!")
                for i, item in enumerate(suggestions, 1):
                    st.markdown(f"**{i}.** {item}")
                
                if st.session_state.is_pro:
                    df_sug = pd.DataFrame({"Suggestion": suggestions})
                    st.download_button("📥 Download Suggestions CSV", df_sug.to_csv(index=False).encode('utf-8'), f"suggestions_{query}.csv", "text/csv")
            else:
                st.warning("No suggestions found.")

        # Välilehti 2: Google Trends
        with tab2:
            st.subheader("YouTube Search Interest (Past 30 Days)")
            with st.spinner("Fetching Google Trends..."):
                trend_data = get_youtube_trends(query)
            
            if trend_data is not None and not trend_data.empty:
                st.line_chart(trend_data.set_index('date'))
                st.success("Trend data loaded successfully!")
                
                if st.session_state.is_pro:
                    st.download_button("📥 Download Trend Data CSV", trend_data.to_csv(index=False).encode('utf-8'), f"trends_{query}.csv", "text/csv")
            else:
                st.info("No sufficient trend data available for this specific keyword right now.")

        # Välilehti 3: Kilpailija-analyysi
        with tab3:
            st.subheader("Top Competitor Content & Views")
            st.write(f"Analyzed top performing videos matching **{query}** ({target_audience} target):")
            
            competitors = get_competitor_videos(query)
            for comp in competitors:
                with st.container():
                    st.markdown(f"📺 **[{comp['Title']}]({comp['Link']})**")
                    st.caption(f"Channel: {comp['Channel']} | Estimated Reach: **{comp['Estimated Views']}**")
                    st.divider()

        # Välilehti 4: AI Content & PDF Report
        with tab4:
            st.subheader("🤖 AI-Powered Metadata & PDF Report")
            q_cap = query.capitalize()
            
            angles = [
                f"The Ultimate {target_audience} Guide to {q_cap} ({video_length})",
                f"I Tested {q_cap} For 30 Days As A Beginner",
                f"Top 5 Mistakes People Make With {q_cap}",
                f"Why Most Fail At {q_cap} (And How To Fix It)"
            ]

            st.markdown("### ✍️ Catchy Video Titles")
            st.code(f"""1. The Truth About {q_cap} Nobody Is Telling You in 2026
2. I Tried {q_cap} For 7 Days Straight (Shocking Results)
3. How to Master {q_cap} Fast ({target_audience} Edition)
4. Stop Making This HUGE Mistake With {q_cap}!""", language="text")

            st.markdown("### 📄 Optimized Video Description")
            st.code(f"""Welcome back to the channel! Today we explore {query} tailored for {target_audience}. In this {video_length} video, we break down everything step by step.

Timestamps:
0:00 - Introduction to {q_cap}
1:30 - The #1 Biggest Mistake
3:45 - Step-by-Step Walkthrough
8:15 - Final Results & Summary

#shorts #{query.replace(' ', '')} #{q_cap}Guide""", language="text")

            st.markdown("### 🏷️ Recommended Tags")
            st.info(f"{query}, {query} tutorial, how to {query}, best {query} 2026, {query} tips, {query} guide")

            st.divider()
            st.subheader("📥 Export Professional PDF Report")
            if st.session_state.is_pro:
                pdf_bytes = create_pdf_report(query, get_youtube_suggestions(query), angles)
                st.download_button(
                    label="📄 Download Complete PDF Report",
                    data=pdf_bytes,
                    file_name=f"youtube_report_{query}.pdf",
                    mime="application/octet-stream"
                )
            else:
                st.warning("🔒 PDF export is available exclusively for **Pro** users. Upgrade in the sidebar to download full reports!")

        # Välilehti 5: Revenue Calculator (Uusi)
        with tab5:
            st.subheader("💰 Channel Revenue & Growth Estimator")
            st.write("Estimate potential AdSense earnings and analyze growth milestones for your channel based on monthly views.")
            
            monthly_views = st.slider("Estimated Monthly Views", 1000, 5000000, 50000, step=5000)
            cpm = st.slider("Estimated CPM ($ per 1,000 views)", 1.0, 25.0, 4.5)
            
            monthly_revenue = (monthly_views / 1000) * cpm
            yearly_revenue = monthly_revenue * 12
            
            col1, col2 = st.columns(2)
            col1.metric("Estimated Monthly AdSense", f"${monthly_revenue:,.2f}")
            col2.metric("Estimated Yearly AdSense", f"${yearly_revenue:,.2f}")
            
            st.info("💡 **Growth Tip:** To increase your CPM in the **" + query + "** niche, focus on long-form tutorials (8+ minutes) and target high-value audience segments.")

        # Välilehti 6: Viral Idea Generator (Uusi)
        with tab6:
            st.subheader("🎲 Random Viral Video Concept Generator")
            st.write(f"Need an instant spark for **{query}**? Generate a unique concept on demand:")
            
            if st.button("Generate Random Concept 🚀"):
                hooks = ["I spent 100 hours testing", "Why everyone is wrong about", "The dark side of", "I built a 10x better"]
                formats = ["Challenge Video", "Deep-Dive Documential", "Tier List / Ranking", "Beginner Mistake Guide"]
                thumbnails = ["Close-up shocked face with bright background", "Split screen 'Before vs After'", "Minimalist text with bold red accent outline"]
                
                h = random.choice(hooks)
                f = random.choice(formats)
                t = random.choice(thumbnails)
                
                st.success(f"**Generated Concept:** {h} {query.title()}")
                st.write(- **Format:** {f})
                st.write(f"- **Thumbnail Idea:** {t}")
            else:
                st.caption("Click the button above to roll a fresh video concept!")

        # Välilehti 7: Script & SEO Suite (Uusi)
        with tab7:
            st.subheader("📝 AI Script Outline & Title SEO Scorecard")
            
            st.markdown("### 1. Title SEO Score Analyzer")
            test_title = st.text_input("Test your video title:", f"The Ultimate Guide to {query.title()}")
            
            score = 50
            feedback = []
            if len(test_title) < 20:
                feedback.append("⚠️ Title is too short (aim for 40-60 characters).")
                score -= 15
            elif len(test_title) > 70:
                feedback.append("⚠️ Title is too long and might get cut off on mobile.")
                score -= 10
            else:
                feedback.append("✅ Optimal title length.")
                score += 20
                
            if any(char.isdigit() for char in test_title):
                feedback.append("✅ Contains numbers (great for click-through rate).")
                score += 15
            else:
                feedback.append("💡 Consider adding a number (e.g., 'Top 5' or '2026') to boost CTR.")
                
            st.metric("Estimated SEO Score", f"{min(score, 100)} / 100")
            for f_item in feedback:
                st.write(f_item)
                
            st.divider()
            st.markdown("### 2. Instant Video Script Outline")
            st.write(f"Standard structure for a **{video_length}** video about **{query}**:")
            st.code(f"""[0:00 - 0:30] THE HOOK
- State the core problem or shocking statement regarding {query}.
- Tell the viewer why they need to watch until the end.

[0:30 - 2:00] THE CONTEXT / WHY IT MATTERS
- Brief background on {query} for {target_audience}.
- Establish your credibility or personal test results.

[2:00 - 8:00] THE CORE WALKFRONT (Step 1, 2, 3)
- Break down the main topic into actionable steps.
- Keep pacing fast with B-roll or visual examples.

[8:00 - End] CALL TO ACTION & OUTRO
- Summarize the main takeaway in one sentence.
- Ask viewers to subscribe and point them to your next recommended video.""", language="text")
