import requests
import streamlit as st
import pandas as pd
from pytrends.request import TrendReq
from fpdf import FPDF
import urllib.parse
from openai import OpenAI

# Sivun asetukset
st.set_page_config(
    page_title="YouTube Analyzer Pro 2026", 
    page_icon="🔴", 
    layout="wide"
)

# Istunnon tila
if 'search_count' not in st.session_state:
    st.session_state.search_count = 0
if 'is_pro' not in st.session_state:
    st.session_state.is_pro = False

# 1. Autocomplete-haku
def get_youtube_suggestions(query):
    url = f"https://suggestqueries.google.com/complete/search?client=firefox&q={urllib.parse.quote(query)}"
    headers = {'User-Agent': 'Mozilla/5.0'}
    try:
        response = requests.get(url, headers=headers, timeout=5)
        if response.status_code == 200:
            return response.json()[1]
    except:
        return []
    return []

# 2. Google Trends (YouTube) -haku
def get_youtube_trends(keyword):
    try:
        pytrends = TrendReq(hl='en-US', tz=360)
        pytrends.build_payload([keyword], cat=0, timeframe='today 1-m', geo='', gprop='youtube')
        data = pytrends.interest_over_time()
        if not data.empty:
            return data.drop(columns=['isPartial']).reset_index()
    except Exception:
        return None
    return None

# 3. Kilpailijahaku
def get_competitor_videos(query):
    suggestions = get_youtube_suggestions(query)
    competitors = []
    base_views = 120000
    for i, s in enumerate(suggestions[:5]):
        competitors.append({
            "Title": f"The Complete Guide to {s.title()}",
            "Channel": f"Creator Lab {i+1}",
            "Estimated Views": f"{base_views - (i * 15000):,} views",
            "Link": f"https://www.youtube.com/results?search_query={urllib.parse.quote(s)}"
        })
    if not competitors:
        competitors.append({
            "Title": f"The Ultimate {query.title()} Masterclass",
            "Channel": "Pro Insights",
            "Estimated Views": "250,000 views",
            "Link": f"https://www.youtube.com/results?search_query={urllib.parse.quote(query)}"
        })
    return competitors

# 4. PDF-raportin generointi Pro-käyttäjille
def create_pdf_report(query, suggestions, ai_titles):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt=f"YouTube Strategy Report: {query.upper()}", ln=True, align='C')
    pdf.set_font("Arial", size=10)
    pdf.cell(200, 10, txt="Generated by YouTube Analyzer Pro 2026", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="1. Top Autocomplete Keywords:", ln=True)
    pdf.set_font("Arial", size=10)
    for s in suggestions[:10]:
        pdf.cell(200, 8, txt=f"- {s}", ln=True)
        
    pdf.ln(5)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="2. AI Generated Content Preview:", ln=True)
    pdf.set_font("Arial", size=9)
    for line in ai_titles.split('\n')[:15]:
        pdf.cell(200, 6, txt=line[:90], ln=True)
        
    return bytes(pdf.output())

# Pääotsikko
st.title("🔴 YouTube Keyword, Trend & AI Analyzer Pro")
st.markdown("### Powered by Real OpenAI Integration & Creator Suite")

# Sivupalkki
st.sidebar.header("Account & Settings")
openai_api_key = st.sidebar.text_input("OpenAI API Key", type="password", placeholder="sk-...")

if st.sidebar.button("Toggle Pro Mode (Test)"):
    st.session_state.is_pro = not st.session_state.is_pro
    st.rerun()

if st.session_state.is_pro:
    st.sidebar.success("⭐ Pro Account Active")
else:
    st.sidebar.info("Free Tier: 2 searches allowed")

st.sidebar.divider()
st.sidebar.markdown("### Creator Settings")
target_audience = st.sidebar.selectbox("Target Audience Style", ["Beginners", "Advanced/Pros", "Gamers / Tech", "General Public"])
video_length = st.sidebar.selectbox("Target Video Length", ["Shorts (< 1 min)", "Standard (8-15 min)", "Deep-dive / Masterclass (20+ min)"])

FREE_LIMIT = 2
if not st.session_state.is_pro and st.session_state.search_count >= FREE_LIMIT:
    st.error("🚨 Free search limit reached!")
    st.warning("Upgrade to Pro or toggle Pro mode in the sidebar to continue.")
else:
    query = st.text_input("Enter a niche, band, or keyword (e.g., eppu normaali, python coding, fitness):", "")

    if query:
        if not st.session_state.is_pro:
            st.session_state.search_count += 1
            st.info(f"Free searches left: {FREE_LIMIT - st.session_state.search_count}")

        # Välilehdet
        tab1, tab2, tab3, tab4, tab5, tab6, tab7 = st.tabs([
            "🔍 Search Suggestions", 
            "📈 YouTube Trends", 
            "🏆 Competitor Analysis", 
            "🤖 AI Metadata & PDF",
            "💰 Revenue Calculator",
            "🎲 Viral Idea Generator",
            "📝 Script & SEO Suite"
        ])

        # Välilehti 1: Autocomplete
        with tab1:
            st.subheader("What people are typing right now")
            with st.spinner("Fetching live autocomplete data..."):
                suggestions = get_youtube_suggestions(query)
            
            if suggestions:
                st.success(f"Found {len(suggestions)} suggestions!")
                for i, item in enumerate(suggestions, 1):
                    st.markdown(f"**{i}.** {item}")
            else:
                st.warning("No suggestions found.")

        # Välilehti 2: Google Trends
        with tab2:
            st.subheader("YouTube Search Interest (Past 30 Days)")
            with st.spinner("Fetching Google Trends..."):
                trend_data = get_youtube_trends(query)
            
            if trend_data is not None and not trend_data.empty:
                st.line_chart(trend_data.set_index('date'))
                st.success("Trend data loaded successfully!")
            else:
                st.info("No sufficient trend data available for this specific keyword right now.")

        # Välilehti 3: Kilpailija-analyysi
        with tab3:
            st.subheader("Top Competitor Content & Views")
            competitors = get_competitor_videos(query)
            for comp in competitors:
                with st.container():
                    st.markdown(f"📺 **[{comp['Title']}]({comp['Link']})**")
                    st.caption(f"Channel: {comp['Channel']} | Estimated Reach: **{comp['Estimated Views']}**")
                    st.divider()

        # Apufunktio OpenAI kutsuille
        def call_openai(prompt_text):
            if not openai_api_key:
                return "⚠️ Please enter your OpenAI API Key in the sidebar to generate AI content!"
            try:
                client = OpenAI(api_key=openai_api_key)
                response = client.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[{"role": "user", "content": prompt_text}],
                    temperature=0.7
                )
                return response.choices[0].message.content
            except Exception as e:
                return f"Error communicating with OpenAI: {e}"

        # Välilehti 4: AI Content & PDF Report
        with tab4:
            st.subheader("🤖 OpenAI-Powered Metadata & Strategy")
            
            if st.button("Generate AI Metadata 🚀"):
                with st.spinner("OpenAI is crafting titles and descriptions..."):
                    prompt = f"Create 4 catchy YouTube video titles, an optimized video description with timestamps, and recommended tags for the topic '{query}'. Target audience: {target_audience}. Video length: {video_length}."
                    ai_metadata = call_openai(prompt)
                    st.session_state['ai_metadata'] = ai_metadata
            
            current_metadata = st.session_state.get('ai_metadata', "Click the button above to generate metadata using your OpenAI key.")
            st.code(current_metadata, language="text")

            st.divider()
            st.subheader("📥 Export Professional PDF Report")
            if st.session_state.is_pro:
                pdf_bytes = create_pdf_report(query, get_youtube_suggestions(query), current_metadata)
                st.download_button(
                    label="📄 Download Complete PDF Report",
                    data=pdf_bytes,
                    file_name=f"youtube_report_{query}.pdf",
                    mime="application/octet-stream"
                )
            else:
                st.warning("🔒 PDF export available for Pro users.")

        # Välilehti 5: Revenue Calculator
        with tab5:
            st.subheader("💰 Channel Revenue & Growth Estimator")
            monthly_views = st.slider("Estimated Monthly Views", 1000, 5000000, 50000, step=5000)
            cpm = st.slider("Estimated CPM ($ per 1,000 views)", 1.0, 25.0, 4.5)
            
            monthly_revenue = (monthly_views / 1000) * cpm
            yearly_revenue = monthly_revenue * 12
            
            col1, col2 = st.columns(2)
            col1.metric("Estimated Monthly AdSense", f"${monthly_revenue:,.2f}")
            col2.metric("Estimated Yearly AdSense", f"${yearly_revenue:,.2f}")

        # Välilehti 6: Viral Idea Generator
        with tab6:
            st.subheader("🎲 AI Viral Video Concept Generator")
            if st.button("Generate AI Concept 💡"):
                with st.spinner("Generating viral angle..."):
                    concept_prompt = f"Give me 1 highly creative viral YouTube video concept, format, and thumbnail idea for the topic '{query}'. Keep it punchy."
                    ai_concept = call_openai(concept_prompt)
                    st.success(ai_concept)
            else:
                st.caption("Click to generate a unique concept via OpenAI.")

        # Välilehti 7: Script & SEO Suite
        with tab7:
            st.subheader("📝 AI Script Outline & Title SEO Scorecard")
            
            test_title = st.text_input("Test your video title:", f"The Ultimate Guide to {query.title()}")
            score = 70 if len(test_title) > 20 else 40
            st.metric("Estimated SEO Score", f"{score} / 100")
            
            st.divider()
            st.markdown("### AI Script Outline")
            if st.button("Generate Full Script Outline ✍️"):
                with st.spinner("Writing script outline..."):
                    script_prompt = f"Create a structured YouTube video script outline (Hook, Body, CTA) for a {video_length} video about '{query}' tailored for {target_audience}."
                    ai_script = call_openai(script_prompt)
                    st.code(ai_script, language="text")
            else:
                st.caption("Click above to generate a tailored script outline with OpenAI.")
